### PR TITLE
.raw`` template literal API with parameters

### PR DESCRIPTION
**Pull request by Jolg42**
Closes prisma/prisma2#1583

### CODE REVIEW

**Comment by RafaelKr** [comment]
You make me very happy with this, thanks! Any ETA for Preview 23 (+-3 days)?

**Comment by Jolg42** [comment]
You can already try it with the alpha version `yarn add prisma2@alpha @prisma/client@alpha` 

Preview 23 should be around that we'll see in a few days! 😉

**Comment by RafaelKr** [comment]
Awesome! How stable are these alpha releases? Do you know of any regression? In particular the compatibility with the nexus plugin :)

**Comment by Jolg42** [comment]
I don't recommend using the alpha in production it's a bit on the edge and sometimes it can be broken too. An alpha is released for each commit.

I think it's better to wait for Preview 23 to get all the details.

**Pull request merged**
